from crewai import Agent
from tools import scan_network_logic, get_vendor_logic, flexible_nmap

LOCAL_MODEL = "ollama/llama3.1:8b"
VISION_MODEL = "ollama/llava:7b"

watcher = Agent(
    role='Network Security Specialist',
    goal='''Scan the subnet {subnet} and identify all devices. Some IoT devices might be in sleep mode.''',
    backstory='You are a cyber-security expert guarding a home network.',
    tools=[scan_network_logic, flexible_nmap],
    llm=LOCAL_MODEL,
    verbose=True,
    max_iter=5,
    allow_delegation=False
)

analyst = Agent(
    role='Cybersecurity Risk Analyst',
    goal='Analyze raw network data to identify potential threats and organize information.',
    backstory='You are a certified security auditor. You look at open ports and device names to find vulnerabilities.',
    llm=LOCAL_MODEL,
    verbose=True
)

suggestor = Agent (
    role="Cybersecurity trouble shooter",
    goal="Suggest actions based on the analysis. Read recommendations from the analyst. Evaluate how usefull suggestions are from analyst and make decisions. Whether actions are needed.",
    backstory='You are a cybersecurity expert who has been trained to suggest solutions for potential threats.',
    verbose=True
)

visual_analyst = Agent(
    role="Senior Microstock Visual Analyst",
    goal="Extract objective, literal visual data from image previews.",
    backstory="You are an elite, cold-eyed Quality Assurance Inspector for a global microstock agency. You have analyzed millions of commercial images. Your job is to look at an image and describe exactly what is physically present in the frame with zero artistic bias, zero poetic language, and absolute technical precision.No poetry, no art, just raw facts.",
    verbose=True,
    max_iter=5,
    allow_delegation=False
)

seo_strategist = Agent(
    role="Director of Stock SEO & Copywriting",
    goal="Transform raw visual descriptions into high-converting commercial titles and keywords.",
    backstory="You are a highly successful Microstock SEO Specialist and Digital Marketer with 10 years of experience optimizing content for Shutterstock, Adobe Stock, and Getty Images. You know exactly how corporate buyers, graphic designers, and advertisers search for visual assets to solve their business problems. You translate literal visual data into high-converting B2B keywords.",
    verbose=True,
    max_iter=5,
    allow_delegation=False
)

legal_auditor = Agent(
    role="Microstock Intellectual Property Counsel",
    goal="Audit metadata for trademarks, copyright risks, and spam, producing the final clean output.",
    backstory="You are the Supreme Legal Counsel and Final Editor for a global microstock agency. You are ruthless, precise, and efficient. Your single task is to take the commercial metadata package generated by the SEO Agent, screen it for property, trademark, and spam violations, and output the **FINAL, CLEANED, PRODUCTION-READY JSON**. You do not delegate back. You fix the errors yourself on the fly.You are a meticulous legal editor. You remove brand names (Apple, Nike, Skoda) and replace them with generic terms. You ensure geographic tags are correct and clean up the syntax.",
    llm=LOCAL_MODEL,
    verbose=True,
    max_iter=5,
    allow_delegation=False
)