import os
from crewai import LLM, Agent
from dotenv import load_dotenv

load_dotenv()

OLLAMA_HOST = os.getenv("OLLAMA_BASE_URL")
VISION_MODEL = os.getenv("VISION_MODEL")
LOCAL_MODEL = os.getenv("LOCAL_MODEL")
LOCAL_MODEL_PLUS = os.getenv("LOCAL_MODEL_PLUS")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL")

LOCAL_MODEL_OBJ = LLM(
    model=LOCAL_MODEL, 
    base_url=OLLAMA_HOST,
    temperature=0.2
)

LOCAL_MODEL_PLUS_OBJ = LLM(
    model=LOCAL_MODEL_PLUS, 
    base_url=OLLAMA_HOST,
    temperature=0.2
)

VISION_MODEL_OBJ = LLM(
    model=VISION_MODEL, 
    base_url=OLLAMA_HOST
)

GEMINI = None
if GEMINI_API_KEY and GEMINI_MODEL:
    try:
        GEMINI = LLM(
            model=GEMINI_MODEL,
            temperature=0.0,
            api_key=GEMINI_API_KEY
        )
    except ImportError:
        GEMINI = None


#----------------------------------------------------- Metadata Agents -----------------------------------------------------

visual_analyst = Agent(
    role="Senior Microstock Visual Analyst",
    goal="Extract objective, literal visual data from image previews.",
    backstory="You are an elite, cold-eyed Quality Assurance Inspector for a global microstock agency. You have analyzed millions of commercial images. Your job is to look at an image and describe exactly what is physically present in the frame with zero artistic bias, zero poetic language, and absolute technical precision.No poetry, no art, just raw facts.",
    verbose=True,
    llm=LOCAL_MODEL_OBJ,
    max_iter=2,
    allow_delegation=False
)

copyright_analyst = Agent(
    role="Senior Microstock Copywriting Specialist",
    goal='''Transform raw visual descriptions from the visual analyst into high-converting commercial titles and keywords.
         Pay attention to metadata for trademarks, copyright risks, and spam, producing the final clean output
         Main goal is to create the most commercial, 
         high-converting metadata possible while strictly following microstock rules.''',
    backstory='''You are a highly successful Microstock SEO Specialist and Digital Marketer
      with 10 years of experience optimizing content for Shutterstock, Adobe Stock, and Getty Images. 
      You know exactly how corporate buyers, graphic designers, and advertisers search for visual assets
      to solve their business problems. 
      You translate literal visual data into high-converting B2B title and keyword metadata.''',
    verbose=True,
    llm=LOCAL_MODEL_PLUS_OBJ,
    max_iter=2,
    allow_delegation=False
)

legal_auditor = Agent(
    role="Senior Microstock Intellectual Property Auditor",
    goal='''Audit metadata for trademarks, copyright risks, and spam, producing the final clean output.Scan the text for real trademarks. If NONE are found, the 'modifications_made' field MUST strictly state "None".''',
    backstory="You are the Supreme Legal Counsel and Final Editor for a global microstock agency. You are ruthless, precise, and efficient. Your single task is to take the commercial metadata package generated by the SEO Agent, screen it for property, trademark, and spam violations, and output the **FINAL, CLEANED, PRODUCTION-READY JSON**. You do not delegate back. You fix the errors yourself on the fly.You are a meticulous legal editor. You remove brand names and replace them with generic terms. You ensure geographic tags are correct and clean up the syntax.",
    llm=LOCAL_MODEL_PLUS_OBJ,
    verbose=True,
    max_iter=2,
    allow_delegation=False
)

metadata_formatter = None
if GEMINI is not None:
    metadata_formatter = Agent(
        role="Chief Microstock Metadata Auditor & Formatter",
        goal="Synthesize raw visual data and chaotic SEO keywords into perfect, high-converting, policy-compliant microstock metadata.",
        backstory="""You are a cynical, highly experienced microstock portfolio manager for Shutterstock and Adobe Stock. 
        You know that 'Keyword Stuffing' or inventing objects that are not in the frame leads to immediate account warnings. 
        Your superpower is taking a messy pile of descriptive words, cross-referencing it with actual image data, 
        and outputting clean, highly commercial titles and single-word keywords that buyers actually type into the search bar.""",
        verbose=True,
        llm=GEMINI,
        max_iter=2,
        allow_delegation=False,
    )